---
sudo: required
dist: bionic
notifications:
  slack:
    on_failure: always
matrix:
  fast_finish: true
  include:

    # The macOS Build Environment
    # https://docs.travis-ci.com/user/reference/osx/
    # Installing Packages on macOS 
    # https://docs.travis-ci.com/user/installing-dependencies/#installing-packages-on-macos
    - name: "kuma w homebrew Python 3.7.5 on macOS 10.15.5 xcode12u "
      os: osx
      osx_image: xcode12u #Xcode build version
      addons:
        homebrew:
          packages:            
            - kumactl
            - minikube
            - kubectl
            - helm3
          update: true
      language: shell  # 'language: python' is an error on Travis CI macOS
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
      install:
        - minikube version 
        - kubectl version --client        
        - pip3 install codecov
        - pip install -r requirements.txt
      script:
        - curl -L https://kuma.io/installer.sh | sh -
        - cd kuma-*/bin #https://kuma.io/docs/0.7.1/installation/macos/
        - ./kuma-cp run & #run Kuma in standalone mode for a "flat" deployment
        # - ln -s ./kumactl /usr/local/bin/kumactl #adding the kumactl executable to your PATH
      after_success:
        - codecov
        - deactivate

    # The macOS Build Environment
    # https://docs.travis-ci.com/user/reference/osx/
    # Installing Packages on macOS 
    # https://docs.travis-ci.com/user/installing-dependencies/#installing-packages-on-macos
    - name: "kuma wo homebrew Python 3.7.5 on macOS 10.15.5 xcode12u "
      os: osx
      osx_image: xcode12u #Xcode build version
      language: shell  # 'language: python' is an error on Travis CI macOS
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
      install:
        - pip3 install codecov
        - pip install -r requirements.txt
      script: 
        # - coverage run tests.py
        - curl -L https://kuma.io/installer.sh | sh -
        - cd kuma-*/bin #https://kuma.io/docs/0.7.1/installation/macos/
        - ./kuma-cp run & #run Kuma in standalone mode for a "flat" deployment        
        - ln -s ./kumactl /usr/local/bin/kumactl #ln: /usr/local/bin/kumactl: File exists
        - |
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-darwin-amd64 \
          && chmod +x minikube && sudo mv minikube /usr/local/bin
          minikube start --vm-driver=none \
                --cpus 6 \
                --memory 12288 \
                --disk-size=120g \
                --extra-config=apiserver.authorization-mode=RBAC \
                --extra-config=kubelet.resolv-conf=/run/systemd/resolve/resolv.conf \
                --extra-config kubeadm.ignore-preflight-errors=SystemVerification          
      after_success:
        - codecov
        - deactivate

    # The macOS Build Environment
    # https://docs.travis-ci.com/user/reference/osx/
    # Installing Packages on macOS 
    # https://docs.travis-ci.com/user/installing-dependencies/#installing-packages-on-macos
    # - name: "Python 3.7.5 on macOS xcode10.2"
    #   os: osx
    #   osx_image: xcode10.2  # travis-ci-macos10.14-xcode10.2-19-1573099784 (via amqp)
    #   language: shell # 'language: python' is an error on Travis CI macOS
    #   before_install:
    #     - pip3 install virtualenv
    #     - virtualenv -p $(which python3) ~venvpy3
    #     - source ~venvpy3/bin/activate
    #   install:
    #     - pip3 install codecov
    #     - pip install -r requirements.txt
    #   script:
    #     - python3 --version
    #     - python2 --version
    #     - python --version
    #     - whoami
    #     - pwd
    #     - pip3 list
    #     # - coverage run tests.py
    #   after_success:
    #     - codecov
    #     - deactivate        

    